# version: '3.8'

# services:
#   nginx:
#     build: ./requirements/nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     depends_on:
#       - wordpress-php-fpm
#     volumes:
#       - wordpress_data:/var/www/html

#   wordpress-php-fpm:
#     build: ./requirements/wordpress
#     expose:
#       - "9000"
#     volumes:
#       - wordpress_data:/var/www/html

# volumes:
#   wordpress_data:
version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress-php-fpm
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  wordpress-php-fpm:
    build: ./requirements/wordpress
    expose:
      - "9000"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  mariadb:
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_USER: root_user
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - wordpress_db_data:/var/lib/mysql
    restart: always

volumes:
  wordpress_db_data:
  wordpress_data:

networks:
  wordpress_network:

